version: "3"

services:
  dvm:
    build: .
    image: ghcr.io/hzrd149/simple-count-dvm
    environment:
      NOSTR_SECRET_KEY: "<hex key>"
      NOSTR_RELAYS: "<relay url>,<relay url>"
    volumes:
      - ./data:/data
